name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/narde-engine:${{ github.ref_name}} .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/narde-engine:${{ github.ref_name}}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
